export const R = {
  engineer: {
    base: "/engineer",
    dashboard: "/engineer/dashboard",
    jobs: "/engineer/jobs",
    calendar: "/engineer/calendar",
    checkin: "/engineer/checkin",
    upload: "/engineer/job/upload",
    messages: "/engineer/messages",
    ai: "/engineer/ai",
    profile: "/engineer/profile",
    network: "/engineer/network",
    learning: "/engineer/learning",
    payments: "/engineer/finance",
    finance: "/engineer/finance",
    reports: "/engineer/reports",
    subscription: "/engineer/subscription",
    help: "/engineer/help",
    settings: "/engineer/settings",
  },
  client: {
    base: "/free",
    dashboard: "/free/dashboard",
    browse: "/free/browse",
    jobs: "/free/myprojects",
    myprojects: "/free/myprojects", // Alias for consistency
    jobNew: "/free/job/new",
    jobCreate: "/free/job/new", // Alias for consistency
    calendar: "/free/calendar",
    messages: "/free/messages",
    ai: "/free/ai",
    profile: "/free/profile",
    network: "/free/network",
    learning: "/free/learning",
    payments: "/free/payments",
    help: "/free/help",
    settings: "/free/settings",
  },
  enterprise: {
    base: "/enterprise",
    dashboard: "/enterprise/dashboard",
    calendar: "/enterprise/calendar",
    teamProjects: "/enterprise/team-projects",
    postProject: "/enterprise/post-project",
    analytics: "/enterprise/analytics",
    messages: "/enterprise/messages",
    ai: "/enterprise/ai",
    employers: "/enterprise/employers",
    procurement: "/enterprise/procurement",
    performance: "/enterprise/performance",
    profile: "/enterprise/profile",
    vendors: "/enterprise/vendors",
    finance: "/enterprise/finance",
    help: "/enterprise/help",
    settings: "/enterprise/settings",
  },
  admin: {
    base: "/admin",
    dashboard: "/admin/dashboard",
    users: "/admin/users",
    projects: "/admin/projects",
    payments: "/admin/payments",
    risk: "/admin/risk",
    settings: "/admin/settings",
  },
} as const;

// Dynamic route helpers for deep links
export const RH = {
  engineer: {
    job: (jobId: string) => `/engineer/jobs/${jobId}`,
    task: (jobId: string, taskId: string) => `/engineer/jobs/${jobId}/tasks/${taskId}`,
    messageThread: (threadId: string) => `/engineer/messages/${threadId}`,
    calendarEvent: (eventId: string) => `/engineer/calendar/event/${eventId}`,
    aiThread: (threadId: string) => `/engineer/ai/thread/${threadId}`,
    learningCourse: (courseId: string) => `/engineer/learning/${courseId}`,
    learningCertificate: (certificateId: string) => `/engineer/learning/certificates/${certificateId}`,
    networkProfile: (userId: string) => `/engineer/network/${userId}`,
    payment: (paymentId: string) => `/engineer/finance/${paymentId}`,
  },
  client: {
    myProject: (projectId: string) => `/free/myprojects/${projectId}`,
    task: (projectId: string, taskId: string) => `/free/myprojects/${projectId}/tasks/${taskId}`,
    messageThread: (threadId: string) => `/free/messages/${threadId}`,
    calendarEvent: (eventId: string) => `/free/calendar/event/${eventId}`,
    aiThread: (threadId: string) => `/free/ai/thread/${threadId}`,
    learningCourse: (courseId: string) => `/free/learning/${courseId}`,
    learningCertificate: (certificateId: string) => `/free/learning/certificates/${certificateId}`,
    networkProfile: (userId: string) => `/free/network/${userId}`,
    payment: (paymentId: string) => `/free/payments/${paymentId}`,
  },
  enterprise: {
    teamProject: (projectId: string) => `/enterprise/team-projects/${projectId}`,
    employer: (employeeId: string) => `/enterprise/employers/${employeeId}`,
    vendor: (vendorId: string) => `/enterprise/vendors/${vendorId}`,
    procurementEntity: (entityId: string) => `/enterprise/procurement/${entityId}`,
    performanceItem: (itemId: string) => `/enterprise/performance/${itemId}`,
    messageThread: (threadId: string) => `/enterprise/messages/${threadId}`,
    calendarEvent: (eventId: string) => `/enterprise/calendar/event/${eventId}`,
    aiThread: (threadId: string) => `/enterprise/ai/thread/${threadId}`,
    payment: (paymentId: string) => `/enterprise/finance/${paymentId}`,
  },
};

