export const R = {
  engineer: {
    base: "/engineer",
    dashboard: "/engineer/dashboard",
    jobs: "/engineer/jobs",
    calendar: "/engineer/calendar",
    checkin: "/engineer/checkin",
    upload: "/engineer/job/upload",
    messages: "/engineer/messages",
    ai: "/engineer/ai",
    profile: "/engineer/profile",
    network: "/engineer/network",
    learning: "/engineer/learning",
    payments: "/engineer/payments",
    help: "/engineer/help",
    settings: "/engineer/settings",
  },
  client: {
    base: "/client",
    dashboard: "/client/dashboard",
    browse: "/client/browse",
    jobs: "/client/jobs",
    jobNew: "/client/job/new",
    calendar: "/client/calendar",
    messages: "/client/messages",
    ai: "/client/ai",
    profile: "/client/profile",
    network: "/client/network",
    learning: "/client/learning",
    payments: "/client/payments",
    help: "/client/help",
    settings: "/client/settings",
  },
  enterprise: {
    base: "/enterprise",
    dashboard: "/enterprise/dashboard",
    projects: "/enterprise/projects",
    workforce: "/enterprise/workforce",
    analytics: "/enterprise/analytics",
    finance: "/enterprise/finance",
    compliance: "/enterprise/compliance",
    messages: "/enterprise/messages",
    settings: "/enterprise/settings",
  },
  admin: {
    base: "/admin",
    dashboard: "/admin/dashboard",
    users: "/admin/users",
    projects: "/admin/projects",
    payments: "/admin/payments",
    risk: "/admin/risk",
    settings: "/admin/settings",
  },
} as const;


