name: Code Quality Bot

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]
  schedule:
    # Run daily at 2 AM UTC
    - cron: '0 2 * * *'

jobs:
  code-quality:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'pnpm'
      
      - name: Install pnpm
        run: npm install -g pnpm
      
      - name: Install dependencies
        run: pnpm install --frozen-lockfile
      
      - name: Run Code Quality Bot
        run: node scripts/code-quality-bot.cjs
        continue-on-error: true
      
      - name: TypeScript Type Check
        run: npx tsc --noEmit
      
      - name: ESLint Check
        run: npx eslint src/ --max-warnings 0
        continue-on-error: true
      
      - name: Upload Report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: code-quality-report
          path: |
            code-quality-report.txt
          retention-days: 30
      
      - name: Comment PR
        if: github.event_name == 'pull_request' && failure()
        uses: actions/github-script@v7
        with:
          script: |
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: '⚠️ Code quality checks failed. Please review the uploaded report for details.'
            })

