name: E2E Nightly
on:
  schedule:
    - cron: '0 3 * * *'
jobs:
  e2e:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v4
        with:
          version: 9
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'pnpm'
      - run: pnpm install --frozen-lockfile
      - name: Start dev server
        run: pnpm dev &
      - name: Wait for server
        run: npx wait-on http://localhost:8081
      - name: Apply Supabase migrations (placeholder)
        run: echo "apply supabase migrations here via CLI or SQL"
      - name: Install Playwright browsers
        run: pnpm exec playwright install --with-deps
      - name: Run Playwright
        env:
          PLAYWRIGHT_BASE_URL: http://localhost:8081
        run: pnpm exec playwright test --project=chromium
